[package]
name = "api"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
hyper = { version = "0.14.25", features = ["full"] }
pretty_env_logger = "0.4.0"
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread"] }
