[package]
name = "api"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
actix-cors = "0.6"
actix-web = "4"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
