[package]
name = "api"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
actix-cors = "0.6"
actix-web = "4"
chrono = { version = "0.4", features = ["serde"] }
firestore = "0.30"
futures = "0.3.28"
once_cell = "1.17.1"
serde = { version = "1", features = ["derive"] }
uuid = { version = "1", features = ["v4", "serde"] }
